language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.4.0

sudo: false
notifications:
  recipients:
    - self@falood.me
before_script:
  - mix deps.get --only test
script:
  - mix coveralls.travis
env:
  - MIX_ENV=test
